// Isolated Dummy Data Set for Demo Accounts (admin@example.com & guru@example.com)
// Ensures Super Admin (saga7o) real database data is strictly private and never exposed in Demo mode.

export const DUMMY_SCHOOLS = [
  {
    id: "demo-school-001",
    name: "SMK Negeri 1 Surabaya",
    school_code: "SMKN1-SBY",
    city: "Kota Surabaya",
    province: "Jawa Timur",
    address: "Jl. SMEA No. 4, Wonokromo, Surabaya",
    phone: "031-8292038",
    email: "info@smkn1surabaya.sch.id",
    principal_name: "Drs. Eko Wahyudi, M.Pd.",
    status: "ACTIVE",
    created_at: "2024-01-15T08:00:00Z",
  },
  {
    id: "demo-school-002",
    name: "SMK Negeri 2 Bandung",
    school_code: "SMKN2-BDG",
    city: "Kota Bandung",
    province: "Jawa Barat",
    address: "Jl. Cihampelas No. 2, Bandung",
    phone: "022-4203847",
    email: "kontak@smkn2bandung.sch.id",
    principal_name: "H. Asep Ridwan, S.T., M.M.",
    status: "ACTIVE",
    created_at: "2024-01-16T08:00:00Z",
  },
  {
    id: "demo-school-003",
    name: "SMK Mitra Industri MM2100",
    school_code: "SMK-MM2100",
    city: "Kabupaten Bekasi",
    province: "Jawa Barat",
    address: "Kawasan Industri MM2100, Cikarang Barat",
    phone: "021-8998394",
    email: "admissions@smkmitraindustri.sch.id",
    principal_name: "Darwoto, S.E., M.M.",
    status: "ACTIVE",
    created_at: "2024-01-17T08:00:00Z",
  },
  {
    id: "demo-school-004",
    name: "SMK Negeri 1 Tengaran",
    school_code: "SMKN1-TGR",
    city: "Kabupaten Semarang",
    province: "Jawa Tengah",
    address: "Jl. Raya Salatiga - Solo Km. 8, Tengaran",
    phone: "0298-340129",
    email: "smkn1tengaran@sch.id",
    principal_name: "Dra. Farida Nur Aini",
    status: "ACTIVE",
    created_at: "2024-01-18T08:00:00Z",
  },
  {
    id: "demo-school-005",
    name: "BLK Don Bosco",
    school_code: "BLK-DB",
    city: "Kabupaten Sumba Barat",
    province: "Nusa Tenggara Timur",
    address: "Jl. Don Bosco No. 1, Waikabubak",
    phone: "0387-21938",
    email: "blk.donbosco@vokasi.or.id",
    principal_name: "Br. Stefanus, SDB",
    status: "ACTIVE",
    created_at: "2024-01-19T08:00:00Z",
  },
];

export interface CompanyBranchItem {
  id: string;
  branch_name: string;
  address: string;
  city?: string | null;
  province?: string | null;
  contact_person?: string | null;
  phone?: string | null;
}

export const DUMMY_COMPANIES = [
  {
    id: "demo-comp-kja",
    name: "PT Kelola Jasa Artha",
    company_code: "KJA",
    industry: "Jasa Pengelolaan Kas & Logistik Nilai Tinggi",
    city: "Jakarta Pusat",
    province: "DKI Jakarta",
    address: "Jl.Ir H Juanda No.28 Kebon Kelapa Gambir Jakarta Pusat 10120 ( Gd.Bank Indonesia )",
    contact_name: "HRD PT Kelola Jasa Artha",
    contact_email: "recruitment@kelolajasaartha.co.id",
    contact_phone: "021-3849201",
    quota: 50,
    status: "ACTIVE",
    created_at: "2024-01-01T08:00:00Z",
    branches: [
      {
        id: "kja-b-01",
        branch_name: "KJA - JAKARTA",
        address:
          "Jl.Ir H Juanda No.28 Kebon Kelapa Gambir Jakarta Pusat 10120 ( Gd.Bank Indonesia )",
        city: "Jakarta Pusat",
      },
      {
        id: "kja-b-02",
        branch_name: "KJA - CIREBON",
        address: "JL.Cideng Raya No.139, Kec, Kedawung, Kab, Cirebon 45153, Jawa Barat",
        city: "Kabupaten Cirebon",
      },
      {
        id: "kja-b-03",
        branch_name: "KJA - DENPASAR",
        address: "JL.Gatot Subroto II B No. 10 Denpasar",
        city: "Kota Denpasar",
      },
      {
        id: "kja-b-04",
        branch_name: "KJA - BANDUNG",
        address: "Jl. Terusan Buah Batu No. 248 Bandung",
        city: "Kota Bandung",
      },
      {
        id: "kja-b-05",
        branch_name: "KJA - SEMARANG",
        address: "JL. Dr Wahidin No.42 Kota Semarang",
        city: "Kota Semarang",
      },
      {
        id: "kja-b-06",
        branch_name: "KJA - SURABAYA",
        address: "JL.Sidosermo II/80 Surabaya 60239",
        city: "Kota Surabaya",
      },
      {
        id: "kja-b-07",
        branch_name: "KJA - MEDAN",
        address: "Jl. Sei Rokan No.7 Babura Medan Sunggal, Medan",
        city: "Kota Medan",
      },
      {
        id: "kja-b-08",
        branch_name: "KJA - MALANG",
        address: "JL. Raung No.7 Malang Jawa Timur",
        city: "Kota Malang",
      },
      {
        id: "kja-b-09",
        branch_name: "KJA - MAKASSAR",
        address: "JL.Abdullah Daeng Sirua No.256 B Pandang, Makassar",
        city: "Kota Makassar",
      },
      {
        id: "kja-b-10",
        branch_name: "KJA - PALEMBANG",
        address:
          "JL.Soekarno Hatta, Lr Sultan Hasanuddin No.2433 RT036, RW 011, Kel Karya Baru, Kec Alang-Alang lebar Palembang Sumatra Selatan",
        city: "Kota Palembang",
      },
      {
        id: "kja-b-11",
        branch_name: "KJA - YOGYAKARTA",
        address:
          "Ring Road Barat No.209 Somodaran RT.06 / RW.11 Banyuraden - Gamping Selatan Yogyakarta",
        city: "Kabupaten Sleman",
      },
      {
        id: "kja-b-12",
        branch_name: "KJA - LAMPUNG",
        address: "JL. M.H Thamrin 86 Kel Gotong Royong Tanjung Karang Bandar Lampung",
        city: "Kota Bandar Lampung",
      },
      {
        id: "kja-b-13",
        branch_name: "KJA - KUPANG",
        address: "JL. Ade Irma No.2 Kelapa Lima Kupang NTT",
        city: "Kota Kupang",
      },
      {
        id: "kja-b-14",
        branch_name: "KJA - TASIKMALAYA",
        address: "JL.BKR No.8 Tasikmalaya",
        city: "Kota Tasikmalaya",
      },
      {
        id: "kja-b-15",
        branch_name: "KJA - SUKABUMI",
        address: "JL. Masjid No.19 Sukabumi Jawa Barat",
        city: "Kota Sukabumi",
      },
      {
        id: "kja-b-16",
        branch_name: "KJA - PARE-PARE",
        address: "JL.Singa No.30 Labukkang Ujung, Kota Pare-Pare Sulawesi Selatan 91111",
        city: "Kota Pare-Pare",
      },
      {
        id: "kja-b-17",
        branch_name: "KJA - SOLO",
        address: "JL.Ir H Juanda No.326 Kel.Pucangsawit Kec. Jebres Kota Surakarta",
        city: "Kota Surakarta",
      },
      {
        id: "kja-b-18",
        branch_name: "KJA - BANJARBARU",
        address:
          "jalan pangeran samudera, kertak hilir kota banjarmasin sebelum lampu merah hotel A ( https://maps.app.goo.gl/wynXjsdzZV4EtG28A ) | JL. Mawar No. 5 Komet, Kec. Banjarbaru Utara, Kota Banjar Baru, Kalimantan Selatan 70714",
        city: "Kota Banjarbaru",
      },
      {
        id: "kja-b-19",
        branch_name: "KJA - PALEMBANG (Oyo)",
        address:
          "JL. Sultan Hasanuddin No. 2433 RT 36 RW 11 Kec. Alang-Alang Lebar, Kel. Karya Baru, Palembang (Belakang Oyo Madinah) https://maps.app.goo.gl/L6usPDhMuCasagnX6",
        city: "Kota Palembang",
      },
    ],
  },
  {
    id: "demo-comp-acs",
    name: "PT Abacus Cash Solution",
    company_code: "ACS",
    industry: "Cash Management & Financial Logistics",
    city: "Kota Bandung",
    province: "Jawa Barat",
    address: "JL. Terusan Jakarta No.57 Bandung, 40291, Jawa Barat",
    contact_name: "Operational Manager ACS",
    contact_email: "info@abacus-cash.co.id",
    contact_phone: "022-7208910",
    quota: 30,
    status: "ACTIVE",
    created_at: "2024-01-02T08:00:00Z",
    branches: [
      {
        id: "acs-b-01",
        branch_name: "ACS - BANDUNG",
        address: "JL. Terusan Jakarta No.57 Bandung, 40291, Jawa Barat",
        city: "Kota Bandung",
      },
      {
        id: "acs-b-02",
        branch_name: "ACS - KEDIRI",
        address: "JL. Raya Kediri Kertosono KM.5 No.36, Gampengrejo, Kediri, 64182",
        city: "Kabupaten Kediri",
      },
      {
        id: "acs-b-03",
        branch_name: "ACS - SURABAYA",
        address: "JL. Anjasmoro No.14a, Sawahan, Surabaya, 60251",
        city: "Kota Surabaya",
      },
    ],
  },
  {
    id: "demo-comp-001",
    name: "PT Astra Honda Motor (Demo)",
    company_code: "AHM",
    industry: "Otomotif & Manufaktur",
    city: "Jakarta Utara",
    province: "DKI Jakarta",
    address: "Jl. Laksda Yos Sudarso, Sunter I, Jakarta Utara",
    contact_name: "Budi Santoso, S.T. (HRD)",
    contact_phone: "021-6518080",
    contact_email: "recruitment.vokasi@astra-honda-demo.com",
    quota: 25,
    status: "ACTIVE",
    created_at: "2024-01-10T08:00:00Z",
    branches: [
      {
        id: "ahm-b-01",
        branch_name: "AHM - PLANT SUNTER",
        address: "Jl. Laksda Yos Sudarso, Sunter I, Jakarta Utara",
        city: "Jakarta Utara",
      },
      {
        id: "ahm-b-02",
        branch_name: "AHM - PLANT CIKARANG",
        address: "Kawasan Industri MM2100, Cikarang Barat",
        city: "Kabupaten Bekasi",
      },
    ],
  },
];

export const DUMMY_STUDENTS = [
  {
    id: "demo-stu-001",
    school_id: "demo-school-001",
    student_number: "BMI-DEMO-001",
    name: "ACHMAD FAUZI PRATAMA",
    gender: "L",
    birth_date: "2007-04-12",
    phone: "0812-3456-7891",
    email: "achmad.fauzi@demo-student.id",
    competency: "Kelas XII",
    status: "ACTIVE",
    schools: { name: "SMK Negeri 1 Surabaya", school_code: "SMKN1-SBY", city: "Kota Surabaya" },
    batch_id: "Batch 01 (Demo)",
    mentor: "Hani",
    city: "Kota Surabaya",
    program_status: "Aktif Akademi",
    talent_pool_year: "2024",
    driving_r4: "Bisa Mengemudi",
    sim_a: "Memiliki",
    sim_c: "Memiliki",
    theory_score: "88",
    interview_score: "92",
    graduation_status: "Lulus",
  },
  {
    id: "demo-stu-002",
    school_id: "demo-school-002",
    student_number: "BMI-DEMO-002",
    name: "SITI NURHALIZA PUTRI",
    gender: "P",
    birth_date: "2007-08-20",
    phone: "0813-8899-1122",
    email: "siti.nurhaliza@demo-student.id",
    competency: "Kelas XII",
    status: "ACTIVE",
    schools: { name: "SMK Negeri 2 Bandung", school_code: "SMKN2-BDG", city: "Kota Bandung" },
    batch_id: "Batch 01 (Demo)",
    mentor: "Aldi",
    city: "Kota Bandung",
    program_status: "Talent Pool",
    talent_pool_year: "2024",
    driving_r4: "Tidak Bisa",
    sim_a: "Tidak Memiliki",
    sim_c: "Memiliki",
    theory_score: "94",
    interview_score: "90",
    graduation_status: "Lulus",
  },
  {
    id: "demo-stu-003",
    school_id: "demo-school-003",
    student_number: "BMI-DEMO-003",
    name: "DIMAS BAGAS PANGESTU",
    gender: "L",
    birth_date: "2006-11-05",
    phone: "0821-4455-6677",
    email: "dimas.bagas@demo-student.id",
    competency: "Alumni",
    status: "ACTIVE",
    schools: {
      name: "SMK Mitra Industri MM2100",
      school_code: "SMK-MM2100",
      city: "Kabupaten Bekasi",
    },
    batch_id: "Batch 01 (Demo)",
    mentor: "Rian",
    city: "Kabupaten Bekasi",
    program_status: "Vokasi",
    talent_pool_year: "2023",
    driving_r4: "Bisa Mengemudi",
    sim_a: "Memiliki",
    sim_c: "Memiliki",
    theory_score: "85",
    interview_score: "88",
    graduation_status: "Lulus",
  },
  {
    id: "demo-stu-004",
    school_id: "demo-school-004",
    student_number: "BMI-DEMO-004",
    name: "MOHAMAD ARDIYANTO",
    gender: "L",
    birth_date: "2007-02-15",
    phone: "0812-2536-4647",
    email: "m.ardiyanto@demo-student.id",
    competency: "Kelas XI",
    status: "ACTIVE",
    schools: {
      name: "SMK Negeri 1 Tengaran",
      school_code: "SMKN1-TGR",
      city: "Kabupaten Semarang",
    },
    batch_id: "Batch 02 (Demo)",
    mentor: "Aldi",
    city: "Kabupaten Semarang",
    program_status: "Aktif Akademi",
    talent_pool_year: "2025",
    driving_r4: "Tidak Bisa",
    sim_a: "Tidak Memiliki",
    sim_c: "Memiliki",
    theory_score: "80",
    interview_score: "82",
    graduation_status: "Lulus",
  },
  {
    id: "demo-stu-005",
    school_id: "demo-school-005",
    student_number: "BMI-DEMO-005",
    name: "FADIL ANWAR KURNIA",
    gender: "L",
    birth_date: "2006-03-21",
    phone: "0852-7788-9900",
    email: "fadil.anwar@demo-student.id",
    competency: "Kelas XII",
    status: "INACTIVE",
    schools: { name: "BLK Don Bosco", school_code: "BLK-DB", city: "Kabupaten Sumba Barat" },
    batch_id: "Batch 01 (Demo)",
    mentor: "Hani",
    city: "Kabupaten Sumba Barat",
    program_status: "Mundur",
    talent_pool_year: "2024",
    driving_r4: "Bisa Mengemudi",
    sim_a: "Tidak Memiliki",
    sim_c: "Memiliki",
    theory_score: "75",
    interview_score: "70",
    graduation_status: "Tidak Lulus",
  },
  {
    id: "demo-stu-006",
    school_id: "demo-school-001",
    student_number: "BMI-DEMO-006",
    name: "RIZKY ADITYA WIJAYA",
    gender: "L",
    birth_date: "2007-06-18",
    phone: "0813-1122-3344",
    email: "rizky.aditya@demo-student.id",
    competency: "Kelas XII",
    status: "ACTIVE",
    schools: { name: "SMK Negeri 1 Surabaya", school_code: "SMKN1-SBY", city: "Kota Surabaya" },
    batch_id: "Batch 02 (Demo)",
    mentor: "Hani",
    city: "Kota Surabaya",
    program_status: "Talent Pool",
    talent_pool_year: "2024",
    driving_r4: "Bisa Mengemudi",
    sim_a: "Memiliki",
    sim_c: "Memiliki",
    theory_score: "91",
    interview_score: "95",
    graduation_status: "Lulus",
  },
  {
    id: "demo-stu-007",
    school_id: "demo-school-002",
    student_number: "BMI-DEMO-007",
    name: "NABILA AYU LESTARI",
    gender: "P",
    birth_date: "2007-09-10",
    phone: "0878-9900-1122",
    email: "nabila.ayu@demo-student.id",
    competency: "Kelas XII",
    status: "ACTIVE",
    schools: { name: "SMK Negeri 2 Bandung", school_code: "SMKN2-BDG", city: "Kota Bandung" },
    batch_id: "Batch 01 (Demo)",
    mentor: "Aldi",
    city: "Kota Bandung",
    program_status: "Vokasi",
    talent_pool_year: "2024",
    driving_r4: "Tidak Bisa",
    sim_a: "Tidak Memiliki",
    sim_c: "Memiliki",
    theory_score: "89",
    interview_score: "91",
    graduation_status: "Lulus",
  },
];

export const DUMMY_INTERNSHIPS = [
  {
    id: "demo-int-001",
    student_id: "demo-stu-001",
    company_id: "demo-comp-001",
    school_id: "demo-school-001",
    competency: "Kelas XII",
    status: "ACTIVE",
    batch_no: "Batch 01 (Demo)",
    training_center: "SMK Negeri 1 Surabaya",
    participant_name: "ACHMAD FAUZI PRATAMA",
    mentor: "Hani",
    city: "Kota Surabaya",
    driving_skill: "Bisa Mengemudi (SIM A)",
    student_status: "Kelas XII",
    target_pkt: "PT Astra Honda Motor (Demo)",
    jobdesk: "Teknisi Perakitan Mesin & Otomasi",
    placement_month: "Januari 2025",
    email: "achmad.fauzi@demo-student.id",
    phone: "0812-3456-7891",
    internship_status: "Aktif Magang",
    students: { name: "ACHMAD FAUZI PRATAMA", student_number: "BMI-DEMO-001" },
    companies: { name: "PT Astra Honda Motor (Demo)" },
    schools: { name: "SMK Negeri 1 Surabaya" },
  },
  {
    id: "demo-int-002",
    student_id: "demo-stu-002",
    company_id: "demo-comp-002",
    school_id: "demo-school-002",
    competency: "Kelas XII",
    status: "SUBMITTED",
    batch_no: "Batch 01 (Demo)",
    training_center: "SMK Negeri 2 Bandung",
    participant_name: "SITI NURHALIZA PUTRI",
    mentor: "Aldi",
    city: "Kota Bandung",
    driving_skill: "Tidak Bisa Mengemudi",
    student_status: "Kelas XII",
    target_pkt: "PT Telkom Indonesia Tbk (Demo)",
    jobdesk: "Junior Network Engineer & IT Support",
    placement_month: "Februari 2025",
    email: "siti.nurhaliza@demo-student.id",
    phone: "0813-8899-1122",
    internship_status: "Peserta Baru",
    students: { name: "SITI NURHALIZA PUTRI", student_number: "BMI-DEMO-002" },
    companies: { name: "PT Telkom Indonesia Tbk (Demo)" },
    schools: { name: "SMK Negeri 2 Bandung" },
  },
  {
    id: "demo-int-003",
    student_id: "demo-stu-003",
    company_id: "demo-comp-003",
    school_id: "demo-school-003",
    competency: "Alumni",
    status: "COMPLETED",
    batch_no: "Batch 01 (Demo)",
    training_center: "SMK Mitra Industri MM2100",
    participant_name: "DIMAS BAGAS PANGESTU",
    mentor: "Rian",
    city: "Kabupaten Bekasi",
    driving_skill: "Bisa Mengemudi (SIM A)",
    student_status: "Alumni",
    target_pkt: "PT United Tractors Tbk (Demo)",
    jobdesk: "Mekanik Alat Berat & Maintenance",
    placement_month: "Agustus 2024",
    email: "dimas.bagas@demo-student.id",
    phone: "0821-4455-6677",
    internship_status: "Selesai",
    students: { name: "DIMAS BAGAS PANGESTU", student_number: "BMI-DEMO-003" },
    companies: { name: "PT United Tractors Tbk (Demo)" },
    schools: { name: "SMK Mitra Industri MM2100" },
  },
  {
    id: "demo-int-004",
    student_id: "demo-stu-006",
    company_id: "demo-comp-001",
    school_id: "demo-school-001",
    competency: "Kelas XII",
    status: "ACTIVE",
    batch_no: "Batch 02 (Demo)",
    training_center: "SMK Negeri 1 Surabaya",
    participant_name: "RIZKY ADITYA WIJAYA",
    mentor: "Hani",
    city: "Kota Surabaya",
    driving_skill: "Bisa Mengemudi (SIM A)",
    student_status: "Kelas XII",
    target_pkt: "PT Astra Honda Motor (Demo)",
    jobdesk: "Quality Control & Logistik Part",
    placement_month: "Maret 2025",
    email: "rizky.aditya@demo-student.id",
    phone: "0813-1122-3344",
    internship_status: "Aktif Magang",
    students: { name: "RIZKY ADITYA WIJAYA", student_number: "BMI-DEMO-006" },
    companies: { name: "PT Astra Honda Motor (Demo)" },
    schools: { name: "SMK Negeri 1 Surabaya" },
  },
  {
    id: "demo-int-005",
    student_id: "demo-stu-007",
    company_id: "demo-comp-004",
    school_id: "demo-school-002",
    competency: "Kelas XII",
    status: "APPROVED",
    batch_no: "Batch 01 (Demo)",
    training_center: "SMK Negeri 2 Bandung",
    participant_name: "NABILA AYU LESTARI",
    mentor: "Aldi",
    city: "Kota Bandung",
    driving_skill: "Tidak Bisa Mengemudi",
    student_status: "Kelas XII",
    target_pkt: "PT Bank Central Asia Tbk (Demo)",
    jobdesk: "Customer Service Support & Administrasi",
    placement_month: "Januari 2025",
    email: "nabila.ayu@demo-student.id",
    phone: "0878-9900-1122",
    internship_status: "Peserta Pengganti",
    students: { name: "NABILA AYU LESTARI", student_number: "BMI-DEMO-007" },
    companies: { name: "PT Bank Central Asia Tbk (Demo)" },
    schools: { name: "SMK Negeri 2 Bandung" },
  },
];

export const DUMMY_DASHBOARD_STATS = {
  totalSchools: 5,
  totalStudents: 7,
  totalCompanies: 4,
  activeInternships: 2,
  pendingApprovals: 1,
  completedInternships: 1,
  rejected: 0,
  approved: 1,
  draft: 0,
  submitted: 1,
  successRate: 100,
  unplacedStudents: 2,
  averageScore: 91.5,
  statusChart: [
    { name: "Draft", value: 0 },
    { name: "Diajukan", value: 1 },
    { name: "Disetujui", value: 1 },
    { name: "Berjalan", value: 2 },
    { name: "Selesai", value: 1 },
    { name: "Ditolak", value: 0 },
  ],
  trendChart: [
    { name: "2024-08", value: 1 },
    { name: "2025-01", value: 2 },
    { name: "2025-02", value: 1 },
    { name: "2025-03", value: 1 },
  ],
  competencyChart: [
    { name: "Kelas XII", value: 5 },
    { name: "Alumni", value: 1 },
    { name: "Kelas XI", value: 1 },
  ],
};

export const DUMMY_USERS = [
  {
    id: "demo-admin-id",
    name: "Admin Pusat (Demo)",
    email: "admin@example.com",
    role: "ADMIN",
    status: "ACTIVE",
    school_id: null,
    schools: null,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "demo-guru-id",
    name: "Guru Pembimbing (Demo)",
    email: "guru@example.com",
    role: "GURU",
    status: "ACTIVE",
    school_id: "demo-school-001",
    schools: { name: "SMK Negeri 1 Surabaya" },
    created_at: "2024-01-01T00:00:00Z",
  },
];
