// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

function getMiddlewareHelper(opts?: any) {
  try {
    if (typeof createMiddleware === "function") {
      const res = createMiddleware(opts);
      if (res && (typeof res.client === "function" || typeof res.server === "function")) {
        return res;
      }
    }
  } catch {
    // fallback if createMiddleware throws during isomorphic evaluation
  }
  return {
    client: (client: any) => ({ options: { ...(opts || {}), client } }),
    server: (server: any) => ({ options: { ...(opts || {}), server } }),
  };
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = getMiddlewareHelper({ type: "function" }).client(
  async ({ next }: any) => {
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
